# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 04:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Swing',
            fields=[
                ('swing', models.IntegerField(primary_key=True, serialize=False)),
                ('data', models.TextField()),
                ('batSpeed', models.FloatField()),
            ],
            options={
                'db_table': 'swings',
                'default_related_name': 'swings',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userId', models.IntegerField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=50)),
                ('firstName', models.CharField(max_length=20)),
                ('lastName', models.CharField(max_length=20)),
                ('profileImageUrl', models.CharField(max_length=120)),
            ],
            options={
                'db_table': 'users',
                'default_related_name': 'users',
            },
        ),
        migrations.AddField(
            model_name='swing',
            name='user',
            field=models.ForeignKey(db_column=b'user', on_delete=django.db.models.deletion.DO_NOTHING, related_name='swings', to='internetOfSwings.User'),
        ),
    ]
